# Generated by Django 4.0 on 2021-12-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('quota', models.PositiveIntegerField(default=134217728)),
                ('is_enabled', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain')),
            ],
            options={
                'db_table': 'users',
                'unique_together': {('username', 'domain')},
            },
        ),
    ]
