# Generated by Django 4.0 on 2021-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('alias', models.EmailField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aliases',
                'unique_together': {('email', 'alias')},
            },
        ),
    ]
